attention_resolutions: 32,16,8
base_samples: ''
batch_size: 30
clip_denoised: true
data_dir: ''
diffusion_steps: 1000
dropout: 0.0
lr_data_dir: input
direction: axial  # axial=(x,y), cor=(x,z), sag=(y,z)
image_size: 256
in_channel: 1
learn_sigma: true
model_path: checkpoints/ema_0.9999_530000.pt
noise_schedule: linear
num_channels: 96
num_head_channels: 48
num_heads: 4
num_heads_upsample: -1
num_res_blocks: 2
num_samples: 300
predict_xstart: false
resblock_updown: true
rescale_learned_sigmas: false
rescale_timesteps: false
sampling_method: guided
timestep_respacing: '20'
use_checkpoint: false
use_fp16: false
use_kl: false
use_scale_shift_norm: true
unet2: 1
mask: true
t1: true
b2: true
grace: true
